# Header
menu:
  首页: /
  文章存档: /archives/
  云标签: /tags/
  关于网站: /about/
rss: /atom.xml

# Content
excerpt_link: 阅读详情»
fancybox: false

# Sidebar
sidebar: left # left or right
widgets:
# - category
- recent_posts
# - tag
# - tagcloud
- archive
# Miscellaneous
google_analytics: 'UA-46263481-3'
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#  自定义字段
since: 2013-2016
author: Feitai
